use_frameworks!

platform :ios, '8.0'

target 'BHFoundation_Example' do
  pod 'BHFoundation', :path => '../'

  target 'BHFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
